[package]
name = "ntt"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"

rand = "0.9.0"
num-primes = "0.3.0"

[features]
default = ["avx2"]
avx2 = []
goldilocks = []

[[bench]]
name = "ntt"
harness = false
